MVCWebUI/Models/CardListViewModel.cs
using Entities.DomainModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebUI.Models
{
    public class CardListViewModel
    {
        public Cart Cart { get; set; }
    }
}

MVCWebUI/Models/CategoryListViewModel.cs
using Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebUI.Models
{
    public class CategoryListViewModel
    {
        public List<Category> Categories { get; set; }
        public int CurrentCategory { get; set; }
    }
}

MVCWebUI/Models/ErrorViewModel.cs
using System;

namespace MVCWebUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCWebUI/Models/ProductListViewModel.cs
using Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebUI.Models
{
    public class ProductListViewModel
    {
       public List<Product> Products { get; set; }
    }
}

MVCWebUI/Models/ShippingDetail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebUI.Models
{
    public class ShippingDetail
    {
        //[Required(ErrorMessage ="İsim alanı zorunludur.")]
        public string FirstName { get; set; }
        //[Required(ErrorMessage = "Soyisim alanı zorunludur.")]
        public string LastName { get; set; }
        //[Required]
        //[DataType(DataType.EmailAddress)]
        public string Email { get; set; }
       // [Required]
        public string City { get; set; }
        //[Required]
        //[MinLength(10,ErrorMessage ="Minimum 10 karakter uzunlugunda olmalı")]
        public string Address { get; set; }
        //[Required]
        //[Range(18,65)]
        public int Age { get; set; }
    }
}

MVCWebUI/Models/ShippingDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebUI.Models
{
    public class ShippingDetailsViewModel
    {
        public ShippingDetail ShippingDetail { get; set; }
    }
}

MVCWebUI/Controllers/CartController.cs
using Business.Abstract;
using Entities.Concrete;
using Microsoft.AspNetCore.Mvc;
using MVCWebUI.Helpers;
using MVCWebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebUI.Controllers
{
    public class CartController : Controller
    {
        private ICartService _cartService;
        private ICartSessionHelper _cartSessionHelper;
        private IProductService _productService;

        public CartController(ICartService cartService, ICartSessionHelper cartSessionHelper, IProductService productService)
        {
            _cartService = cartService;
            _cartSessionHelper = cartSessionHelper;
            _productService = productService;
        }

        public IActionResult AddToCart(int productId)
        {
            //ürünü çek 
            Product product = _productService.GetById(productId);

            var cart = _cartSessionHelper.GetCart("cart");
            _cartService.AddToCart(cart,product);

            _cartSessionHelper.SetCart("cart",cart);
            TempData.Add("message",product.ProductName +" sepete Eklendi");

            return RedirectToAction("Index" ,"Product");
        }

        public IActionResult Index()
        {
            var model = new CardListViewModel
            {
                Cart = _cartSessionHelper.GetCart("cart")
            };
            return View(model);
        }

        public IActionResult RemoveFromCart(int productId)
        {
            //ürünü çek 
            Product product = _productService.GetById(productId);
            var cart = _cartSessionHelper.GetCart("cart");
            _cartService.RemoveFromCart(cart, productId);

            _cartSessionHelper.SetCart("cart", cart);
            TempData.Add("message", product.ProductName + " sepetten Çıkarıldı.");
            return RedirectToAction("Index", "Cart");
        }

        public IActionResult Complete()
        {
            var model = new ShippingDetailsViewModel
            {
                ShippingDetail = new ShippingDetail()
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Complete(ShippingDetail shippingDetail)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            TempData.Add("message", "Siparişiniz başarıyla tamamlandı.");
            _cartSessionHelper.Clear();
            return RedirectToAction("Index","Cart");
        }
    }
}

MVCWebUI/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Abstract;
using MVCWebUI.Models;
using DataAccess.Abstract;

namespace MVCWebUI.Controllers
{
    public class CategoryController : Controller
    {
        private ICategoryDal  _categoryDal;

        public CategoryController(ICategoryDal categoryDal)
        {
            _categoryDal = categoryDal;
        }

       
    }
}

MVCWebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCWebUI.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCWebUI/Controllers/ProductController.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using MVCWebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Index(int category)
        {
            var model = new ProductListViewModel
            {
                Products = category > 0 ? _productService.GetByCategory(category) : _productService.GetAll()
            };
            return View(model);
        }
    }
}

MVCWebUI/ViewComponents/CategoryListViewComponent.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using MVCWebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebUI.ViewComponents
{
    public class CategoryListViewComponent :ViewComponent
    {
        private ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public ViewViewComponentResult Invoke()
        {

            var model = new CategoryListViewModel
            {
                Categories = _categoryService.GetAll(),
                CurrentCategory =Convert.ToInt32(HttpContext.Request.Query["category"])
            };
            return View(model);
        }
    }
}

MVCWebUI/Views/Cart/Complete.cshtml
@model ShippingDetailsViewModel
@{
    ViewData["Title"] = "Complete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Complete</h1>

<form asp-controller="Cart" asp-action="Complete" method="post">
    <div class="form-group">
        <label asp-for="ShippingDetail.FirstName">Ad</label>
        <input type="text" asp-for="ShippingDetail.FirstName" class="form-control" placeholder="Müşteri Adı" />
        <span asp-validation-for="ShippingDetail.FirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShippingDetail.LastName">Soyad</label>
        <input type="text" asp-for="ShippingDetail.LastName" class="form-control" placeholder="Müşteri Soyad" />
        <span asp-validation-for="ShippingDetail.LastName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShippingDetail.Email">E-posta</label>
        <input type="text" asp-for="ShippingDetail.Email" class="form-control" placeholder="E-posta" />
        <span asp-validation-for="ShippingDetail.Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShippingDetail.Age">Yaş</label>
        <input type="text" asp-for="ShippingDetail.Age" class="form-control" placeholder="Müşteri Yaş" />
        <span asp-validation-for="ShippingDetail.Age" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShippingDetail.City">Şehir</label>
        <input type="text" asp-for="ShippingDetail.City" class="form-control" placeholder="Yaşadığınız Şehir" />
        <span asp-validation-for="ShippingDetail.City" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShippingDetail.Address">Adres</label>
        <input type="text" asp-for="ShippingDetail.Address" class="form-control" placeholder="Adres" />
        <span asp-validation-for="ShippingDetail.Address" class="text-danger"></span>
    </div>
    <input type="submit" name="name" value="Kaydet" class="btn btn-sm btn-success" />
</form>

MVCWebUI/Views/Cart/Index.cshtml
@model CardListViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Sepetiniz</h1>
@if (Model.Cart.CartLines.Count == 0)
{
    <h2 class="badge badge-danger">Sepetiniz ürün bulunmamaktadır.</h2>
}
else
{
    <table class="table table-responsive-lg">
        <thead>
            <tr>
                <th>ID</th>
                <th>Ürün Adı</th>
                <th>Açıklama</th>
                <th>Fiayt</th>
                <th>Stok</th>
                <th>Toplam</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var cartline in Model.Cart.CartLines)
            {
                <tr>
                    <td>@cartline.Product.ProductId</td>
                    <td>@cartline.Product.ProductName</td>
                    <td>@cartline.Product.QuantityPerUnit</td>
                    <td>@cartline.Product.UnitPrice</td>
                    <td>@cartline.Product.UnitsInStock</td>
                    <td>@cartline.Quantity</td>
                    <td><a class="btn btn-sm btn-danger" asp-controller="Cart" asp-action="RemoveFromCart" asp-route-productId="@cartline.Product.ProductId">SİL</a></td>
                </tr>
            }

        </tbody>
    </table>

}

MVCWebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVCWebUI/Views/Product/Index.cshtml
@model ProductListViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Ürünler</h1>
<table class="table table-responsive-lg">
    <thead>
        <tr>
            <th>ID</th>
            <th>Ürün Adı</th>
            <th></th>
            <th></th>
            <th>Stok</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Products)
        {
            <tr>
                <td>@item.ProductId</td>
                <td>@item.ProductName</td>
                <td>@item.QuantityPerUnit</td>
                <td>@item.UnitPrice</td>
                <td>@item.UnitsInStock</td>
                <td><a class="btn btn-sm btn-success" asp-controller="Cart" asp-action="AddToCart" asp-route-productId="@item.ProductId">Sepete ekle</a></td>
            </tr>
        }

    </tbody>
</table>

MVCWebUI/Views/Shared/Components/CategoryList/Default.cshtml
@model CategoryListViewModel


<h1>Kategoriler</h1>


<div class="list-group">
    <a href="/Product/Index/" class="list-group-item">Tüm Ürünler</a>

    @foreach (var item in Model.Categories)
    {
        var css = "list-group-item";
        if (item.CategoryID == Model.CurrentCategory)
        {
            css += " active";

        }
        <a href="/Product/Index?category=@item.CategoryID" class="@css">@item.CategoryName</a>
    }

</div>
       
  

MVCWebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCWebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCWebUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Product">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Sepete Git</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="row">
                @if (TempData["message"] != null)
                {
                <div class="alert alert-primary">
                    @TempData["message"]
                </div>
                }
            </div>
            <div class="row">
                <div class="col-3">@await Component.InvokeAsync("CategoryList")</div>
                <div class="col-9"> @RenderBody()</div>
            </div>
           
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVCWebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>